version: '3'

services:
  #nginx:
  #  container_name: nginx
  #  restart: unless-stopped
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - build/:/usr/share/nginx/html 
  quasar:
    container_name: quasar
    restart: unless-stopped
    dockerfile: quasarApp/Dockerfile
  adonis:
    container_name: adonis
    restart: unless-stopped
    dokcerfile: adonisApi/Dockerfile
    